# Generated by Django 4.2.6 on 2023-12-24 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name="Mark",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("marks", models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name="Semester",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                ("std_rollno", models.IntegerField(primary_key=True, serialize=False)),
                ("std_name", models.CharField(max_length=255)),
                ("std_father_name", models.CharField(max_length=255)),
                ("std_mother_name", models.CharField(max_length=255)),
                ("std_age", models.DateField()),
                ("std_mobile", models.IntegerField()),
                ("std_address", models.CharField(max_length=500)),
                ("std_course", models.CharField(max_length=255)),
                (
                    "std_image",
                    models.FileField(
                        blank=True,
                        default=None,
                        max_length=250,
                        null=True,
                        upload_to="profile_images/",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Year",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField()),
                (
                    "course",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="student.course",
                        verbose_name="Student",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(max_length=250)),
                ("semester", models.ManyToManyField(to="student.semester")),
            ],
        ),
        migrations.AddField(
            model_name="semester",
            name="year",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="student.year"
            ),
        ),
        migrations.CreateModel(
            name="Result",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("grade", models.CharField(max_length=50)),
                (
                    "marks",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="student.mark"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="mark",
            name="subject",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="student.subject"
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="student",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="student.student",
                verbose_name="Student",
            ),
        ),
    ]
