# Generated by Django 4.2.7 on 2023-12-03 13:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("student", "0002_result"),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                ("description", models.CharField(max_length=500)),
                (
                    "image",
                    models.FileField(
                        blank=True,
                        default=None,
                        max_length=250,
                        null=True,
                        upload_to="courses/",
                    ),
                ),
            ],
        ),
    ]
