# Generated by Django 4.2.6 on 2023-12-24 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("student", "0002_remove_student_std_course"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subject",
            name="semester",
        ),
        migrations.AddField(
            model_name="subject",
            name="semester",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="student.semester",
                verbose_name="Semester",
            ),
            preserve_default=False,
        ),
    ]
