# Generated by Django 4.2.7 on 2023-12-03 13:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("student", "0003_course"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="description",
            field=models.CharField(max_length=1000),
        ),
    ]
