# Generated by Django 4.2.6 on 2023-12-24 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("student", "0003_remove_subject_semester_subject_semester"),
    ]

    operations = [
        migrations.AlterField(
            model_name="semester",
            name="year",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="student.year",
                verbose_name="Year",
            ),
        ),
    ]
