# Generated by Django 4.2.7 on 2023-12-03 13:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("student", "0004_alter_course_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="description",
            field=models.TextField(),
        ),
    ]
