# Generated by Django 4.2.7 on 2023-12-04 15:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("student", "0005_alter_course_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="Semester",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
            ],
        ),
        migrations.RemoveField(
            model_name="course",
            name="description",
        ),
        migrations.RemoveField(
            model_name="course",
            name="image",
        ),
        migrations.RemoveField(
            model_name="result",
            name="std_fullmarks",
        ),
        migrations.RemoveField(
            model_name="result",
            name="std_grade",
        ),
        migrations.RemoveField(
            model_name="result",
            name="std_marksobtained",
        ),
        migrations.RemoveField(
            model_name="result",
            name="std_passmarks",
        ),
        migrations.RemoveField(
            model_name="result",
            name="std_subject",
        ),
        migrations.RemoveField(
            model_name="result",
            name="student",
        ),
        migrations.AddField(
            model_name="course",
            name="student",
            field=models.ManyToManyField(to="student.student", verbose_name="Student"),
        ),
        migrations.AddField(
            model_name="result",
            name="course",
            field=models.ManyToManyField(to="student.course", verbose_name="Course"),
        ),
        migrations.AddField(
            model_name="result",
            name="marks",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="result",
            name="semster",
            field=models.ManyToManyField(to="student.semester", verbose_name="Course"),
        ),
    ]
