# Generated by Django 4.2.6 on 2023-12-24 12:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("student", "0006_student_semester"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="semester",
        ),
    ]
