# Generated by Django 4.2.6 on 2023-12-24 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("student", "0007_remove_student_semester"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="semester",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="student.semester",
                verbose_name="Semester",
            ),
            preserve_default=False,
        ),
    ]
