# Generated by Django 4.2.7 on 2023-12-04 15:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("student", "0010_rename_marks_mark_marks1_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="mark",
            old_name="marks1",
            new_name="marks",
        ),
        migrations.RenameField(
            model_name="subject",
            old_name="subject1",
            new_name="subject",
        ),
        migrations.RemoveField(
            model_name="mark",
            name="marks2",
        ),
        migrations.RemoveField(
            model_name="mark",
            name="marks3",
        ),
        migrations.RemoveField(
            model_name="mark",
            name="marks4",
        ),
        migrations.RemoveField(
            model_name="subject",
            name="subject2",
        ),
        migrations.RemoveField(
            model_name="subject",
            name="subject3",
        ),
        migrations.RemoveField(
            model_name="subject",
            name="subject4",
        ),
    ]
