# Generated by Django 4.2.7 on 2023-12-04 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("student", "0011_rename_marks1_mark_marks_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="student",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="student.student",
            ),
            preserve_default=False,
        ),
    ]
