# Generated by Django 4.2.7 on 2023-12-05 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("student", "0015_remove_semester_year_semester_course_delete_year"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="semester",
            name="course",
        ),
        migrations.CreateModel(
            name="Year",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField()),
                (
                    "course",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="student.course",
                        verbose_name="Student",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="semester",
            name="year",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="student.year",
            ),
            preserve_default=False,
        ),
    ]
